### ISSUE TITLE
2.1 release

### ISSUE THREAD

**Issue by neumino** [neumino/rethinkdbdash#108]
RethinkDB is soon going to release it (a RC is coming soon I think).
For 2.1 there are a few things to do:

- [x] Update the pools to handle the new format for `server_status` - See #107
- [x] Switch the discovery to a changefeed for better reactivity
- [x] For the pool master to go through all the seeds if no pool is available to fetch `server_status` - See #107
- [x] Add an option for `r.js` to timeout
- [x] Add `ceil`/`floor`/`round`
- [x] Update backtraces
- [x] Handle new sub-types errors - See https://github.com/rethinkdb/rethinkdb/issues/4472

**Comment by neumino** [comment]
Just pushed for the new error types. Everything is ready for 2.1 as far as I know.
If you want to play with it, it's in the branch `raft` (not `next`).

**Comment by tlperkins** [comment]
Didn't see it listed, but does the raft  branch have support for SSL?

**Comment by ha1331** [comment]
Any idea when this will be available at npm?

**Comment by neumino** [comment]
It's out. Wercker seems to have some issues running the tests though.

**Comment by neumino** [comment]
Also yes tls is in. The parameter is named `ssl` (same as in the official driver) - it was in the branch `raftTls`
